# Copyright (C) 2026 Alex Cobb
# Licensed under the BSD 2-Clause License (see LICENSE-BSD.txt)
#
# NOTE: This file is part of the spowtd project. When distributed as a compiled binary
# linked against the GSL, the resulting work is licensed under the GPL-3.0-or-later.

"""Typing stubs for _specific_yield"""

class SpecificYield:
    def __call__(self, zeta: float) -> float: ...
    def storage(self, water_table: float, surface: float) -> float: ...
    def shallow_storage(self, zeta: float) -> float: ...
    def deep_storage(self, surface: float) -> float: ...
    def zeta(self, shallow_storage: float) -> float: ...
